spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  shardingsphere:
    datasource:
      names: ds0,ds1,ds2,ds3
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://127.0.0.1:5432/db0
        username: postgres
        password: postgres
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://127.0.0.1:5432/db1
        username: postgres
        password: postgres
      ds2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://127.0.0.1:5432/db2
        username: postgres
        password: postgres
      ds3:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://127.0.0.1:5432/db3
        username: postgres
        password: postgres
    sharding:
      default-data-source-name: ds0
      default-database-strategy:
        inline:
          sharding-column: user_id
          algorithm-expression: ds$->{user_id % 4}
      defaultTableStrategy:
        inline:
          sharding-column: order_id
          algorithm-expression: t_order_$->{order_id % 10}
      tables:
        t_order:
          actual-data-nodes: ds$->{0..3}.t_order_$->{0..7}
          table-strategy:
            inline:
              sharding-column: order_id
              algorithm-expression: t_order_$->{order_id % 8}
        customer:
          actual-data-nodes: ds$->{0..3}.customer_$->{0..7}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: customer_$->{id % 8}       
      defaultKeyGenerator:
        type: SNOWFLAKE
        column: id                 
  devtools:
    restart:
      enabled: true # 热部署开关，false即不启用热部署
      exclude: test/** # 指定目录不更新
#         additional-paths: src/main/java # 指定热部署的目录
logging:
  path: /opt/log/sharding-service/
  file: /opt/log/sharding-service/dsharding-service.log
  level:
    root: DEBUG
hibernate:
#      org:
#         hibernate: DEBUG
  jdbc:
    lob:
      non_contextual_creation: true
